// src/pages/App.svelte
<script lang="ts">
//console.log("App.svelte.NODE_ENV=", process.env.NODE_ENV);
</script>

<!-- -->
<main>
    <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>welcome</title>
        {#if process.env.NODE_ENV === "develop"}
            <link href="/static/style.css" rel="stylesheet" />
        {:else}
            <link href="/public/static/style.css" rel="stylesheet" />
        {/if}
        </head>
    <body>
        <div id="app"></div>
        {#if process.env.NODE_ENV === "develop"}
            <script type="module" src="/static/Home.js"></script>
        {:else}
            <script type="module" src="/public/static/Home.js"></script>
        {/if}
    </body>
</main>

<style>
</style>
<!--
-->

// sample/simple_auth/src/pages/App.tsx
import * as React from 'react';

console.log("env=", process.env.NODE_ENV)
//
export default function Page() { 
    return (
    <html>
        <head>
            <title>welcome</title>
            {(process.env.NODE_ENV === "develop") ? (
                <link href="/static/main.css" rel="stylesheet" /> 
            ): (
                <link href="/public/static/main.css" rel="stylesheet" /> 
            )} 
        </head>
        <body>
          <div>
            <div id="app"></div>
            {(process.env.NODE_ENV === "develop") ? (
                <script type="module" src="/static/Home.js"></script>
            ): (
                <script type="module" src="/public/static/Home.js"></script> 
            )}             
          </div>
        </body>
    </html>
    );
}
/*
<a href="/">[ home ]</a>
<a href="/about">[ about ]</a>
<a href="/test">[ test ]</a>
<hr />
<h1 className="text-4xl font-bold">Hello!!</h1>
*/
